{{- if .Values.rbac.create }}
{{- if (and .Values.podSecurityPolicy.enable (not .Values.podSecurityPolicy.name)) }}
---
kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
  name: {{ template "instana-agent.podSecurityPolicyName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "instana-agent.commonLabels" . | nindent 4 }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - secret
    - projected
    - hostPath
  allowedHostPaths:
    - pathPrefix: "/dev"
      readOnly: true
    - pathPrefix: "/run"
      readOnly: false
    - pathPrefix: "/var/run"
      readOnly: false
    - pathPrefix: "/var/vcap/sys/run/docker"
      readOnly: false
    - pathPrefix: "/sys"
      readOnly: true
    - pathPrefix: "/var/log"
      readOnly: true
    - pathPrefix: "/var/lib"
      readOnly: true
    - pathPrefix: "/var/data"
      readOnly: true
    - pathPrefix: "/etc/machine-id"
      readOnly: true
    {{- if .Values.agent.host.repository }}
    - pathPrefix: {{ .Values.agent.host.repository }}
      readOnly: false
    {{- end }}
  hostNetwork: true
  hostPorts:
    - min: 0
      max: 65535
  hostPID: true
  runAsUser:
    rule: "RunAsAny"
  seLinux:
    rule: "RunAsAny"
  supplementalGroups:
    rule: "RunAsAny"
  fsGroup:
    rule: "RunAsAny"
{{- end }}
{{- end }}
